---
title: "Coevolution with a seed bank"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Analyze composition of mutations from pooled population sequencing

# Setup Work Environment
```{r}
#rm(list=ls())
getwd()
setwd("~/GitHub/coevo-seedbank-seq/code")

# Load dependencies
require("vegan")
require("dplyr")
require("grid")
require("png")
sem <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}

# Confidence Hulls
add.hull <- function(model = "", pred.frame = ""){
  CI.U <- predict(model, interval = "c", newdata=pred.frame)[, "upr"]
  CI.L <- predict(model, interval = "c", newdata=pred.frame)[, "lwr"]
  pred.frame2 <- unlist(pred.frame)
  X.Vec <- c(pred.frame2, tail(pred.frame2, 1), rev(pred.frame2),
               head(pred.frame2, 1))
  Y.Vec <- c(CI.U, tail(CI.L, 1), rev(CI.L), head(CI.U,1))
  polygon(X.Vec, Y.Vec, col = "gray90", border = NA)
}
```

# Load data
```{r}
mutdat <- read.csv("../data/mult_host.csv")
mut.log <- decostand(mutdat[,2:ncol(mutdat)], method = "log")
```

# Multivariate procedures
```{r}
# Make presence-absence matrix
mut.PA <- (mutmat > 0) * 1

# Define treatments and data
seed <- c(1,1,1,1,1,1,0,0,0,0,0,0)
phage <- c(0,0,0,1,1,1,0,0,0,1,1,1)
mut <- cbind(seed, phage, mutdat[,2:ncol(mutdat)])
#mut <- cbind(seed, phage, mut.log)

# "manhattan", "euclidean", "canberra", "clark", "bray", "kulczynski", "jaccard", "gower", "altGower", "morisita", "horn", "mountford", "raup", "binomial", "chao", "cao", "mahalanobis", "chisq" or "chord".

# Calculate pairwise distances
mut.dist <- vegdist(mut, method = "bray", binary = "FALSE")

# Principal Coordinates Analysis (PCoA)
pc <- cmdscale(mut.dist, eig = TRUE, k = 3)
explainvar1 <- round(pc$eig[1] / sum(pc$eig), 3) * 100
explainvar2 <- round(pc$eig[2] / sum(pc$eig), 3) * 100
explainvar3 <- round(pc$eig[3] / sum(pc$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)
## unclear why two first PCoAs explain >100% variation

# OTU Scores
mut.scores <- t(cor(pc$points, mut))
mut.scores <- as.matrix(mut.scores)[,1:2]
mut.scores <- mut.scores[abs(mut.scores[,1]) > 0.7|abs(mut.scores[,2]) > 0.7,]

# PERMANOVA
seed <- mut[,1]
phage <- mut[,2]
perm <- adonis(mut[,3:ncol(mut)] ~ seed * phage, method = "bray", binary = FALSE)
perm
```

## PCoA Plot
```{r, results = "hide"}
png(filename="../analysis/Jay-ordinations.png",
    width = 1200, height = 1200, res = 96*2)

plot.new()
par(mar = c(7, 7, 5, 7))

plot(pc$points[ ,1], pc$points[ ,2],
     ylim = c(-0.8, 0.8), xlim = c(-0.8, 0.8),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     #xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     pch = 22, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1,
     axes = FALSE)

# Add Axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-0.4",  "0.0", "0.4"), at = c(-0.4, 0, 0.4))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(-0.4, 0, 0.4), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-0.4",  "0.0", "0.4"), at = c(-0.4, 0, 0.4))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(-0.4, 0, 0.4), labels = F)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Identify ordinates by treatment

pc.points <- cbind(mut[,1:2],pc$points)

noseed.nophage <- pc.points %>%
  filter(seed == "0" & phage == "0")

noseed.phage <- pc.points %>%
  filter(seed == "0" & phage == "1")

seed.nophage <- pc.points %>%
  filter(seed == "1" & phage == "0")

seed.phage <- pc.points %>%
  filter(seed == "1" & phage == "1")

# Add points corresponding to treatments
points(noseed.nophage [ ,3], noseed.nophage [ ,4], pch = 21,
       cex = 2, col = "blue", bg = "white", lwd = 2)

points(noseed.phage [ ,3], noseed.phage [ ,4], pch = 22,
       cex = 2, col = "blue", bg = "white", lwd = 2)

points(seed.nophage [ ,3], seed.nophage [ ,4], pch = 21,
       cex = 2, col = "red", bg = "white", lwd = 2)

points(seed.phage [ ,3], seed.phage [ ,4], pch = 22,
       cex = 2, col = "red", bg = "white", lwd = 2)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("../analysis/Jay-ordinations.png")
grid.raster(img)
```
